#!/usr/local/bin/python

"""
Load department data into Django database.

Can be run as a Python script from the command line, i.e.

>python deptscript.py.
"""

import os

os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

from reviews.models import Department

def SetDepartments():

    deptlist = [['African American Studies', 'AFRICAM', 'http://socrates.berkeley.edu/%7Eafricam/'],
    ['Agricultural and Environmental Chemistry', 'AGR CHM', 'http://plantbio.berkeley.edu/newpmb/academic/graduate-agchem.shtml'],
    ['Environmental Economics and Policy', 'ENVECON', 'http://are.berkeley.edu/'],
    ['Agricultural and Resource Economics and Policy', 'A,RESEC', 'http://are.berkeley.edu/'],
    ['American Studies', 'AMERSTD', 'http://ls.berkeley.edu/ugis/as/'],
    ['Ancient History and Mediterranean Archaeology', 'AHMA', 'http://ls.berkeley.edu/dept/ahma/'],
    ['Anthropology', 'ANTHRO', 'http://anthropology.berkeley.edu/'],
    ['Applied Science and Technology', 'AST', 'http://www.coe.berkeley.edu/AST/'],
    ['Architecture', 'ARCH', 'http://arch.ced.berkeley.edu/'],
    ['Visual Studies', 'VIS STD', 'http://arch.ced.berkeley.edu/'],
    ['Practice of Art', 'ART', 'http://art.berkeley.edu/'],
    ['History of Art', 'HISTART', 'http://ls.berkeley.edu/dept/arthistory/'],
    ['Asian American Studies Program', 'ASAMST', 'http://ethnicstudies.berkeley.edu/'],
    ['Asian Studies', 'ASIANST', 'http://ieas.berkeley.edu/gas/'],
    ['Astronomy', 'ASTRON', 'http://astron.berkeley.edu/'],
    ['Bioengineering', 'BIO ENG', 'http://bioeng.berkeley.edu/'],
    ['Biology 1A', 'BIOLOGY', 'http://mcb.berkeley.edu/'],
    ['Biology 1B', 'BIOLOGY', 'http://ib.berkeley.edu/'],
    ['Biology 11', 'BIOLOGY', 'http://plantbio.berkeley.edu/'],
    ['Biophysics', 'BIOPHY', 'http://biophysics.berkeley.edu/'],
    ['Buddhist Studies', 'BUDDSTD', 'http://buddhiststudies.berkeley.edu/'],
    ['Business Administration', 'BUS ADM', 'http://haas.berkeley.edu/'],
    ['Undergraduate Program leading to the Bachelor of Science in Business Administration', 'UGBA', 'http://haas.berkeley.edu/'],
    ['Full-time Masters in Business Administration', 'MBA', 'http://haas.berkeley.edu/'],
    ['Evening/Weekend MBA Program', 'EWMBA', 'http://haas.berkeley.edu/'],
    ['Berkeley/Columbia MBA Program', 'XMBA', 'http://haas.berkeley.edu/'],
    ['Masters in Financial Engineering Program', 'MFE', 'http://haas.berkeley.edu/'],
    ['Doctoral Program in Business Administration', 'PHDBA', 'http://haas.berkeley.edu/'],
    ['Celtic Studies', 'CELTIC', 'http://ls.berkeley.edu/dept/celtic/'],
    ['Chemical and Biomolecular Engineering', 'CHM ENG', 'http://cheme.berkeley.edu/'],
    ['Chemistry', 'CHEM', 'http://chem.berkeley.edu/'],
    ['Chicano Studies Program', 'CHICANO', 'http://ethnicstudies.berkeley.edu/'],
    ['City and Regional Planning', 'CY PLAN', 'http://new-dcrp.ced.berkeley.edu/'],
    ['Civil and Environmental Engineering', 'CIV ENG', 'http://www.ce.berkeley.edu/'],
    ['Classics', 'CLASSIC', 'http://ls.berkeley.edu/dept/classics/'],
    ['Greek', 'GREEK', 'http://ls.berkeley.edu/dept/classics/'],
    ['Latin', 'LATIN', 'http://ls.berkeley.edu/dept/classics/'],
    ['Cognitive Science', 'COG SCI', 'http://ls.berkeley.edu/ugis/cogsci/index.php'],
    ['College Writing Program', 'COLWRIT', 'http://www-writing.berkeley.edu/'],
    ['Comparative Biochemistry', 'COMPBIO', 'http://compbiochem.berkeley.edu/'],
    ['Comparative Literature', 'COM LIT', 'http://complit.berkeley.edu/'],
    ['Computational and Genomic Biology', 'CGB', 'http://computationalbiology.berkeley.edu/'],
    ['Critical Theory Graduate Group', 'CRIT TH', 'http://criticaltheory.berkeley.edu/'],
    ['Demography', 'DEMOG', 'http://www.demog.berkeley.edu/'],
    ['Development Studies', 'DEV STD', 'http://iastp.berkeley.edu/ProgramProfile.asp?code=DS'],
    ['Earth and Planetary Science', 'EPS', 'http://eps.berkeley.edu/'],
    ['East Asian Languages and Cultures', 'EA LANG', 'http://ealc.berkeley.edu/'],
    ['Chinese', 'CHINESE', 'http://ealc.berkeley.edu/'],
    ['Japanese', 'JAPAN', 'http://ealc.berkeley.edu/'],
    ['Altaic', 'ALTAIC', 'http://ealc.berkeley.edu/'],
    ['Korean', 'KOREAN', 'http://ealc.berkeley.edu/'],
    ['Tibetan', 'TIBETAN', 'http://ealc.berkeley.edu/'],
    ['Economics', 'ECON', 'http://elsa.berkeley.edu/econ/'],
    ['Education', 'EDUC', 'http://www-gse.berkeley.edu/'],
    ['Electrical Engineering', 'EL ENG', 'http://www.eecs.berkeley.edu/'],
    ['Computer Science', 'COMPSCI', 'http://www.eecs.berkeley.edu/'],
    ['Energy and Resources Group', 'ENE,RES', 'http://socrates.berkeley.edu/erg/'],
    ['Engineering', 'ENGIN', 'http://www.coe.berkeley.edu/'],
    ['English', 'ENGLISH', 'http://english.berkeley.edu/'],
    ['Environmental Design', 'ENV DES', 'http://www.ced.berkeley.edu/'],
    ['Environmental Science', 'ESPM', 'http://espm.berkeley.edu/'],
    ['Environmental Sciences', 'ENV SCI', 'http://environmentalsciences.berkeley.edu/'],
    ['Ethnic Studies', 'ETH STD', 'http://ethnicstudies.berkeley.edu/'],
    ['Ethnic Studies Graduate Group', 'ETH GRP', 'http://ethnicstudies.berkeley.edu/'],
    ['Film and Media', 'FILM', 'http://filmstudies.berkeley.edu/'],
    ['Folklore', 'FOLKLOR', 'http://ls.berkeley.edu/dept/folklore/index.html'],
    ['French', 'FRENCH', 'http://french.berkeley.edu/'],
    ['Gender and Women\'s Studies', 'GWS', 'http://womensstudies.berkeley.edu/'],
    ['Lesbian', 'LGBT', 'http://womensstudies.berkeley.edu/'],
    ['Geography', 'GEOG', 'http://geography.berkeley.edu/'],
    ['German', 'GERMAN', 'http://german.berkeley.edu/'],
    ['Yiddish', 'YIDDISH', 'http://german.berkeley.edu/'],
    ['Dutch', 'DUTCH', 'http://german.berkeley.edu/'],
    ['Afrikaans', 'AFRKANS', 'http://german.berkeley.edu/'],
    ['Global Metropolitan Studies', 'GMS', 'http://metrostudies.berkeley.edu/'],
    ['Global Poverty and Practice', 'GPP', 'http://blumcenter.berkeley.edu/global-poverty-education/global-poverty-minor'],
    ['Graduate Student Professional Development Program', 'GSPDP', 'http://gsi.berkeley.edu/'],
    ['Language Proficiency Program', 'LAN PRO', 'http://gsi.berkeley.edu/'],
    ['Health and Medical Sciences', 'HMEDSCI', 'http://jmp.berkeley.edu/'],
    ['History', 'HISTORY', 'http://history.berkeley.edu/'],
    ['Industrial Engineering and Operations Research', 'IND ENG', 'http://www.ieor.berkeley.edu/'],
    ['Information', 'INFO', 'http://www.sims.berkeley.edu/'],
    ['Integrative Biology', 'INTEGBI', 'http://ib.berkeley.edu/'],
    ['Interdisciplinary Studies Field Major', 'ISF', 'http://ls.berkeley.edu/dept/isf/index.html'],
    ['International and Area Studies', 'IAS', 'http://www.ias.berkeley.edu/'],
    ['Italian Studies', 'ITALIAN', 'http://ls.berkeley.edu/dept/italian/index.html'],
    ['Jewish Studies', 'JEWISH', 'http://jewishstudies.berkeley.edu/'],
    ['Journalism', 'JOURN', 'http://journalism.berkeley.edu/'],
    ['Landscape Architecture', 'LD ARCH', 'http://new-laep.ced.berkeley.edu/'],
    ['Latin American Studies', 'LATAMST', 'http://iastp.berkeley.edu/ProgramProfile.asp?code=LAS'],
    ['Law', 'LAW', 'http://www.law.berkeley.edu/'],
    ['Legal Studies', 'LEGALST', 'http://legalstudies.berkeley.edu/'],
    ['Letters and Science', 'L & S', 'http://lsdiscovery.berkeley.edu/'],
    ['Linguistics', 'LINGUIS', 'http://www.linguistics.berkeley.edu/'],
    ['Materials Science and Engineering', 'MAT SCI', 'http://www.mse.berkeley.edu/'],
    ['Mathematics', 'MATH', 'http://math.berkeley.edu/'],
    ['Mechanical Engineering', 'MEC ENG', 'http://www.me.berkeley.edu/'],
    ['Media Studies', 'MEDIAST', 'http://ls.berkeley.edu/ugis/masscomm/'],
    ['Medieval Studies', 'MED ST', 'http://ls.berkeley.edu/dept/medieval/'],
    ['Middle Eastern Studies', 'M E STU', 'http://iastp.berkeley.edu/ProgramProfile.asp?code=MES'],
    ['Military Affairs', 'MIL AFF', 'http://military.berkeley.edu/'],
    ['Aerospace Studies', 'AEROSPC', 'http://military.berkeley.edu/'],
    ['Military Science', 'MIL SCI', 'http://military.berkeley.edu/'],
    ['Naval Science', 'NAV SCI', 'http://military.berkeley.edu/'],
    ['Molecular and Cell Biology', 'MCELLBI', 'http://mcb.berkeley.edu/'],
    ['Music', 'MUSIC', 'http://ls.berkeley.edu/dept/music/'],
    ['Nanoscale Science and Engineering', 'NSE', 'http://nano.berkeley.edu/welcome/welcome.html'],
    ['Native American Studies', 'NATAMST', 'http://ethnicstudies.berkeley.edu/'],
    ['Natural Resources', 'NAT RES', 'http://www.cnr.berkeley.edu/'],
    ['Near Eastern Studies', 'NE STUD', 'http://neareastern.berkeley.edu/'],
    ['Arabic', 'ARABIC', 'http://neareastern.berkeley.edu/'],
    ['Cuneiform', 'CUNEIF', 'http://neareastern.berkeley.edu/'],
    ['Egyptian', 'EGYPT', 'http://neareastern.berkeley.edu/'],
    ['Hebrew', 'HEBREW', 'http://neareastern.berkeley.edu/'],
    ['Persian', 'PERSIAN', 'http://neareastern.berkeley.edu/'],
    ['Iranian', 'IRANIAN', 'http://neareastern.berkeley.edu/'],
    ['Semitics', 'SEMITIC', 'http://neareastern.berkeley.edu/'],
    ['Turkish', 'TURKISH', 'http://neareastern.berkeley.edu/'],
    ['Neuroscience', 'NEUROSC', 'http://neuroscience.berkeley.edu/'],
    ['New Media', 'NWMEDIA', 'http://cnm.berkeley.edu/'],
    ['Nuclear Engineering', 'NUC ENG', 'http://www.nuc.berkeley.edu/'],
    ['Nutritional Sciences and Toxicology', 'NUSCTX', 'http://nutrition.berkeley.edu/'],
    ['Optometry', 'OPTOM', 'http://spectacle.berkeley.edu/'],
    ['Vision Science', 'VIS SCI', 'http://spectacle.berkeley.edu/'],
    ['Peace and Conflict Studies', 'PACS', 'http://iastp.berkeley.edu/ProgramProfile.asp?code=PACS'],
    ['Philosophy', 'PHILOS', 'http://philosophy.berkeley.edu/'],
    ['Physical Education', 'PHYS ED', 'http://pe.berkeley.edu/'],
    ['Physics', 'PHYSICS', 'http://physics.berkeley.edu/'],
    ['Plant and Microbial Biology', 'PLANTBI', 'http://plantbio.berkeley.edu/'],
    ['Political Economy of Industrial Societies', 'POLECIS', 'http://iastp.berkeley.edu/ProgramProfile.asp?code=PEIS'],
    ['Political Science', 'POL SCI', 'http://www.polisci.berkeley.edu/'],
    ['Psychology', 'PSYCH', 'http://psychology.berkeley.edu/'],
    ['Public Health', 'PB HLTH', 'http://sph.berkeley.edu/'],
    ['Public Policy', 'PUB POL', 'http://socrates.berkeley.edu/%7Egspp/'],
    ['Religious Studies', 'RELIGST', 'http://ls.berkeley.edu/ugis/religiousstudies/'],
    ['Rhetoric', 'RHETOR', 'http://rhetoric.berkeley.edu/'],
    ['Scandinavian', 'SCANDIN', 'http://ls.berkeley.edu/dept/scandinavian/'],
    ['Science and Mathematics Education', 'SCMATHE', 'http://www-gse.berkeley.edu/program/CD/Programs/SESAME.htm'],
    ['Slavic Languages and Literatures', 'SLAVIC', 'http://ls.berkeley.edu/dept/slavic/index.html'],
    ['East European Studies', 'EAEURST', 'http://ls.berkeley.edu/dept/slavic/index.html'],
    ['Eurasian Studies', 'EURA ST', 'http://ls.berkeley.edu/dept/slavic/index.html'],
    ['Social Welfare', 'SOC WEL', 'http://socialwelfare.berkeley.edu/'],
    ['Sociology', 'SOCIOL', 'http://sociology.berkeley.edu/'],
    ['South and Southeast Asian Studies', 'S,SEASN', 'http://ls.berkeley.edu/dept/sseas/'],
    ['South Asian', 'S ASIAN', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Southeast Asian', 'SEASIAN', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Bengali', 'BANGLA', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Filipino', 'FILIPN', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Hindi-Urdu', 'HIN-URD', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Khmer', 'KHMER', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Malay/Indonesian', 'MALAY/I', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Punjabi', 'PUNJABI', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Sanskrit', 'SANSKR', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Tagalog', 'TAGALG', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Tamil', 'TAMIL', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Telugu', 'TELUGU', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Thai', 'THAI', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Vietnamese', 'VIETNMS', 'http://ls.berkeley.edu/dept/sseas/'],
    ['Spanish', 'SPANISH', 'http://spanish-portuguese.berkeley.edu/'],
    ['Portuguese', 'PORTUG', 'http://spanish-portuguese.berkeley.edu/'],
    ['Catalan', 'CATALAN', 'http://spanish-portuguese.berkeley.edu/'],
    ['Indigenous Languages of the Americas', 'ILA', 'http://spanish-portuguese.berkeley.edu/'],
    ['Statistics', 'STAT', 'http://www.stat.berkeley.edu/'],
    ['Theater', 'THEATER', 'http://theater.berkeley.edu/'],
    ['Undergraduate and Interdisciplinary Studies', 'UGIS', 'http://ls.berkeley.edu/divisions/undergrad/ugis.html']]

    for dept in deptlist:
        # Use get_or_create to avoid duplicating existing entries.
        Department.objects.get_or_create(name=dept[0], abb=dept[1], link=dept[2])

if __name__ == "__main__":
    SetDepartments()
